apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kanidm.fullname" . }}
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
data: 
  server.toml: |-
    {{- tpl (.Files.Get "config/server.toml") . | nindent 4 }}
