{{- if (include "kanidm.shouldCreateCert" .Values.certs.ssl) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-ssl"
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      containers:
      - name: create-ssl
        image: alpine:3.14
        command: ["/bin/sh", "-c"]
        args:
        - |
          {{- tpl (.Files.Get "scripts/create-ssl.sh") . | nindent 10 }}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: ca-volume
          mountPath: /var/ca
          readOnly: true
      volumes:
      - name: ca-volume
        secret:
          secretName: {{ include "kanidm.ca.secretName" . }}
      restartPolicy: Never
{{- end }}
