{{- if and .Values.persistence.enabled  (not .Values.persistence.existingClaimName)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kanidm.fullname" . }}
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}