{{- if and (include "kanidm.existsFromRef" .Values.certs.ca.key) (include "kanidm.existsFromRef" .Values.certs.ca.cert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kanidm.ca.secretName" . }}
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
data:
  key.pem: |
    {{ include "kanidm.getFromRef" .Values.certs.ca.key }}
  cert.pem: |
    {{ include "kanidm.getFromRef" .Values.certs.ca.cert }}
{{- end }}