{{- if and (include "kanidm.existsFromRef" .Values.certs.ca.cert) (include "kanidm.existsFromRef" .Values.certs.ssl.key) (include "kanidm.existsFromRef" .Values.certs.ssl.cert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kanidm.ssl.secretName" . }}
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
data:
  ca.pem: |
    {{ include "kanidm.getFromRef" .Values.certs.ca.cert }}
  key.pem: |
    {{ include "kanidm.getFromRef" .Values.certs.ssl.key }}
  cert.pem: |
    {{ include "kanidm.getFromRef" .Values.certs.ssl.cert }}
{{- end }}